# Generated by Django 5.0.3 on 2024-04-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AIModel', '0002_delete_classifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageClassifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
